const C3 = self.C3;
self.C3_GetObjectRefTable = function () {
	return [
		C3.Plugins.Sprite,
		C3.Behaviors.Platform,
		C3.Behaviors.MoveTo,
		C3.Behaviors.scrollto,
		C3.Behaviors.solid,
		C3.Behaviors.Pin,
		C3.Behaviors.Sin,
		C3.Plugins.Text,
		C3.Plugins.Button,
		C3.Plugins.Tilemap,
		C3.Plugins.Keyboard,
		C3.Plugins.System.Cnds.EveryTick,
		C3.Plugins.System.Acts.Scroll,
		C3.Plugins.Sprite.Exps.X,
		C3.Plugins.Sprite.Exps.Y,
		C3.Plugins.Text.Acts.SetText,
		C3.Plugins.Sprite.Cnds.OnCollision,
		C3.Plugins.System.Acts.RestartLayout,
		C3.Plugins.System.Acts.SetVar,
		C3.Plugins.Sprite.Acts.Destroy,
		C3.Plugins.System.Acts.AddVar,
		C3.Plugins.System.Cnds.OnLayoutStart,
		C3.Behaviors.Pin.Acts.PinByImagePoint,
		C3.Behaviors.Platform.Cnds.IsFalling,
		C3.Behaviors.Platform.Acts.SetVectorY,
		C3.Plugins.System.Cnds.Else,
		C3.Behaviors.Platform.Acts.SetDefaultControls,
		C3.Plugins.System.Acts.Wait,
		C3.Plugins.System.Acts.GoToLayout,
		C3.Plugins.Sprite.Acts.SetPosToObject,
		C3.Plugins.Keyboard.Cnds.OnKey,
		C3.Plugins.Sprite.Acts.SetMirrored,
		C3.Behaviors.Platform.Cnds.OnJump,
		C3.Plugins.Sprite.Acts.SetAnim,
		C3.Behaviors.Platform.Cnds.OnLand,
		C3.Behaviors.Platform.Cnds.OnMove,
		C3.Behaviors.Platform.Cnds.OnStop,
		C3.Plugins.System.Cnds.Compare,
		C3.Plugins.Button.Cnds.OnClicked
	];
};
self.C3_JsPropNameTable = [
	{Plataforma: 0},
	{MoverPara: 0},
	{CentrarEm: 0},
	{Jogador: 0},
	{Sólido: 0},
	{Sprite: 0},
	{Moeda: 0},
	{Sprite3: 0},
	{Sprite4: 0},
	{Lava: 0},
	{Sprite5: 0},
	{Sprite6: 0},
	{Sprite7: 0},
	{Fixar: 0},
	{Sprite8: 0},
	{objetoFinalDoJogo: 0},
	{Sprite9: 0},
	{arvorecGame: 0},
	{Sprite2: 0},
	{Senóide: 0},
	{inimigo: 0},
	{bauFm: 0},
	{Texto: 0},
	{Botão: 0},
	{Texto2: 0},
	{Mosaico: 0},
	{Sprite10: 0},
	{Sprite11: 0},
	{Sprite12: 0},
	{Inimigo3: 0},
	{inimigo4: 0},
	{jogadoranim: 0},
	{Teclado: 0},
	{BCO10c7c6147cc9400081931447aefe5d88removebgpreview: 0},
	{Texto3: 0},
	{pontos: 0}
];

self.InstanceType = {
	Jogador: class extends self.ISpriteInstance {},
	Sprite: class extends self.ISpriteInstance {},
	Moeda: class extends self.ISpriteInstance {},
	Sprite3: class extends self.ISpriteInstance {},
	Sprite4: class extends self.ISpriteInstance {},
	Lava: class extends self.ISpriteInstance {},
	Sprite5: class extends self.ISpriteInstance {},
	Sprite6: class extends self.ISpriteInstance {},
	Sprite7: class extends self.ISpriteInstance {},
	Sprite8: class extends self.ISpriteInstance {},
	objetoFinalDoJogo: class extends self.ISpriteInstance {},
	Sprite9: class extends self.ISpriteInstance {},
	arvorecGame: class extends self.ISpriteInstance {},
	Sprite2: class extends self.ISpriteInstance {},
	inimigo: class extends self.ISpriteInstance {},
	bauFm: class extends self.ISpriteInstance {},
	Texto: class extends self.ITextInstance {},
	Botão: class extends self.IButtonInstance {},
	Texto2: class extends self.ITextInstance {},
	Mosaico: class extends self.ITilemapInstance {},
	Sprite10: class extends self.ISpriteInstance {},
	Sprite11: class extends self.ISpriteInstance {},
	Sprite12: class extends self.ISpriteInstance {},
	Inimigo3: class extends self.ISpriteInstance {},
	inimigo4: class extends self.ISpriteInstance {},
	jogadoranim: class extends self.ISpriteInstance {},
	Teclado: class extends self.IInstance {},
	BCO10c7c6147cc9400081931447aefe5d88removebgpreview: class extends self.ISpriteInstance {},
	Texto3: class extends self.ITextInstance {}
}